require('dotenv').config()
const q = process.env

module.exports = {
    ALCHEMY_API_KEY: q.ALCHEMY_API_KEY,
    GOERLI_DEPLOYER_PRIVATE_KEY: q.GOERLI_DEPLOYER_PRIVATE_KEY,
    GOERLI_EXISTENT_BONNIE_CONTRACT_ADDRESS: q.GOERLI_EXISTENT_BONNIE_CONTRACT_ADDRESS,
    BONNIES_PRIVATE_KEY: q.BONNIES_PRIVATE_KEY,
    BONNIES_ADDRESS: q.BONNIES_ADDRESS,
    BONNIES_BKP_ADDRESS: q.BONNIES_BKP_ADDRESS,
    
}